//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blankspaces.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESTAMO
    {
        public int IDPRESTAMO { get; set; }
        public Nullable<decimal> IDMATBIBLIO { get; set; }
        public string IDUSUARIO { get; set; }
        public string FECHADEPRESTAMO { get; set; }
        public string FECHADEENTREGA { get; set; }
    
        public virtual MATERIALBIBLIOGRAFICO MATERIALBIBLIOGRAFICO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
